### ISSUE TITLE
Update to Eureka 4.x and swift 4.0

### ISSUE THREAD

**Issue by lukaszspaczynski** [apozdeyev/ReactiveEureka#1]
Is it possible?

**Comment by apozdeyev** [comment]
if it doesn't take much time, I will update it today. Also PR will be very much appreciated! :)

**Comment by apozdeyev** [comment]
Unfortunately, there are a few compile errors in ReactiveCocoa with xCode 9. Seems some magic is still needed to make it working with xCode 9 and swift 4 :( I will continue to make it working in next week.

**Comment by lukaszspaczynski** [comment]
@apozdeyev yes, but you can switch the swift lang version to 3.2 for ReactiveCocoa target.

**Comment by apozdeyev** [comment]
@lukaszspaczynski thank you! I will try.

**Comment by apozdeyev** [comment]
@lukaszspaczynski Hi! I've set project swift version to 4 and Eureka version to 4. But unfortunately, there is still error with ReactiveCocoa and swift 4. In podspec we can specify only release version of ReactiveCocoa which uses swift 3.x, and theres is another issue in CocoaPod which sets swift version in ReactiveCocoa pod target to 4. So to fully complete new version of ReactiveEureka we need to wait new release of ReactiveCocoa or CocoaPod.
Anyway I pushed updated project to develop, so you can manually change swift version of ReactiveCocoa pod target to 3 after pod install and it should work after it.

**Comment by apozdeyev** [comment]
Hi @lukaszspaczynski!
Now I have time to continue working on the project and with the latest versions of Eureka and ReactiveCocoa it easily migrated to swift 4!
https://github.com/apozdeyev/ReactiveEureka/releases/tag/0.1.3
